# 시퀀스형
# 예를 들어 어느 백화점에서 파이썬으로 백엔드를 구축했는데, vvip를 dict으로 관리했다. 
# dict은 mutable이기 때문에 언제든지 수정이 가능하다. 
# 그래서 vvip dict를 immutable로 관리하고 싶을 때 파이썬에서 만들어진 immutable dict으로 변경할 수 있다.
# 해시테이블(hashtable) -> 적은 리소스로 많은 데이터를 효율적으로 관리
# Dict -> Key 중복 허용 안됨, Set -> 중복 허용 안됨
# Dict 및 Set 심화

# immutable Dict
from unicodedata import name
from dis import dis  # dis모듈은 바이트 코드가 어떻게 생성되는지 순서를 알 수 있음
from types import MappingProxyType  # 추가, 수정이 안되는 읽기 전용 dict만들 수 있음

d = {'key': 'value1'}

# read only
d_frozen = MappingProxyType(d)
print(d, id(d))  # {'key': 'value1'} 4463582080
# print(hash(d)) # TypeError: unhashable type: 'dict' dic은 mutable이기 때문에 hash불가능

print(d_frozen, id(d_frozen))  # {'key': 'value1'} 4432043888
# print(hash(d_frozen)) # TypeError: unhashable type: 'mappingproxy'
# -> 표면상으로만 readOnly로 바뀌었을 뿐 hash값으로 변환할 수 없다.

# 수정 불가
# d_frozen['key2'] = 'value2' / TypeError: 'mappingproxy' object does not support item assignment

# 수정 가능
d['key2'] = 'value2'
print(d) # {'key': 'value1', 'key2' : 'value2'}

s1 = {'Apple', 'Orange', 'Apple', 'Orange', 'Kiwi'}
s2 = set(['Apple', 'Orange', 'Apple', 'Orange', 'Kiwi'])  # 위와 같음
s3 = {3}
s4 = set()  # Not {} : 이건 dict
s5 = frozenset({'Apple', 'Orange', 'Apple', 'Orange', 'Kiwi'})

s1.add('Melon')
print(s1)  # {'Apple', 'Orange', 'Kiwi', 'Melon'} 중복은 안되지만 추가됨

# 추가 불가
# s5.add('Melon') # AttributeError: 'frozenset' object has no attribute 'add'

print(s1, type(s1))  # {'Apple', 'Orange', 'Kiwi', 'Melon'} <class 'set'>
print(s2, type(s2))  # {'Apple', 'Orange', 'Kiwi'} <class 'set'>
print(s3, type(s3))  # {3} <class 'set'>
print(s4, type(s4))  # set() <class 'set'>
# frozenset({'Apple', 'Orange', 'Kiwi'}) <class 'frozenset'>
print(s5, type(s5))

# 선언 최적화
# 파이썬은 실행될 때 바이트 코드로 실행 됨 -> 파이썬 인터프리터가 실행
# dis: 바이트 코드가 어떻게 실행되는 지 순서 볼 수 있음

print('-------')
print(dis('{10}')) # set 코드를 직접 실행
#   1           0 LOAD_CONST               0 (10)
#              2 BUILD_SET                1
#              4 RETURN_VALUE
print('-------')
print(dis('set([10])')) # list를 set으로 변경
#  1           0 LOAD_NAME                0 (set)
#              2 LOAD_CONST               0 (10)
#              4 BUILD_LIST               1
#              6 CALL_FUNCTION            1
#              8 RETURN_VALUE
# 결론 s2보다 s1을 쓰는 걸 추천.

# 지능형 집합(Comprehending Set)
# 문자열 자판, 이런식으로 지능형 set만들 수 있다.
print({name(chr(i), '') for i in range(0, 256)})
# {'', 'LATIN CAPITAL LETTER R', 'LATIN SMALL LETTER R', 'FULL STOP', 'LATIN CAPITAL LETTER C WITH CEDILLA', 'LATIN CAPITAL LETTER G', 'LATIN SMALL LETTER N WITH TILDE', 'SOLIDUS', 'LATIN SMALL LETTER A WITH RING ABOVE', 'EQUALS SIGN', 'NUMBER SIGN', 'LATIN SMALL LETTER I WITH GRAVE', 'COMMERCIAL AT', 'LATIN SMALL LETTER W', 'LATIN SMALL LETTER U WITH GRAVE', 'MIDDLE DOT', 'FEMININE ORDINAL INDICATOR', 'CURRENCY SIGN', 'DIGIT SIX', 'LATIN CAPITAL LETTER A WITH DIAERESIS', 'LATIN SMALL LETTER P', 'LATIN CAPITAL LETTER AE', 'DIGIT ZERO', 'POUND SIGN', 'LATIN SMALL LETTER Y', 'PILCROW SIGN', 'COLON', 'LATIN SMALL LETTER E WITH CIRCUMFLEX', 'LATIN SMALL LETTER X', 'LATIN SMALL LETTER B', 'LATIN CAPITAL LETTER A WITH RING ABOVE', 'DIGIT THREE', 'LATIN SMALL LETTER Z', 'DIAERESIS', 'LATIN SMALL LETTER C WITH CEDILLA', 'LATIN SMALL LETTER I WITH CIRCUMFLEX', 'LATIN SMALL LETTER Y WITH DIAERESIS', 'LATIN CAPITAL LETTER A', 'LATIN CAPITAL LETTER I WITH ACUTE', 'LATIN SMALL LETTER N', 'RIGHT PARENTHESIS', 'LATIN SMALL LETTER F', 'LATIN CAPITAL LETTER U WITH GRAVE', 'LATIN SMALL LETTER E WITH GRAVE', 'LATIN SMALL LETTER O WITH GRAVE', 'YEN SIGN', 'LATIN CAPITAL LETTER A WITH TILDE', 'LATIN SMALL LETTER A WITH GRAVE', 'LESS-THAN SIGN', 'SUPERSCRIPT THREE', 'MASCULINE ORDINAL INDICATOR', 'LATIN CAPITAL LETTER E WITH DIAERESIS', 'LATIN SMALL LETTER AE', 'LATIN SMALL LETTER E WITH ACUTE', 'LATIN SMALL LETTER K', 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK', 'LATIN CAPITAL LETTER I', 'LATIN CAPITAL LETTER O WITH ACUTE', 'LATIN SMALL LETTER U', 'LATIN SMALL LETTER L', 'COMMA', 'APOSTROPHE', 'LATIN SMALL LETTER A WITH DIAERESIS', 'LATIN CAPITAL LETTER U WITH CIRCUMFLEX', 'DEGREE SIGN', 'SPACE', 'DIGIT FIVE', 'LATIN CAPITAL LETTER E', 'SOFT HYPHEN', 'LATIN CAPITAL LETTER ETH', 'LATIN SMALL LETTER I WITH ACUTE', 'LATIN SMALL LETTER U WITH DIAERESIS', 'LATIN CAPITAL LETTER M', 'LATIN SMALL LETTER ETH', 'PLUS-MINUS SIGN', 'LATIN CAPITAL LETTER V', 'NOT SIGN', 'DIGIT EIGHT', 'LOW LINE', 'LATIN SMALL LETTER I WITH DIAERESIS', 'ASTERISK', 'LATIN SMALL LETTER A WITH CIRCUMFLEX', 'LATIN CAPITAL LETTER U', 'LATIN SMALL LETTER J', 'SUPERSCRIPT TWO', 'LATIN SMALL LETTER V', 'LEFT CURLY BRACKET', 'INVERTED EXCLAMATION MARK', 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX', 'LATIN SMALL LETTER E', 'RIGHT CURLY BRACKET', 'LATIN CAPITAL LETTER A WITH ACUTE', 'LATIN CAPITAL LETTER O WITH GRAVE', 'LATIN CAPITAL LETTER H', 'LATIN SMALL LETTER SHARP S', 'MACRON', 'TILDE', 'LATIN CAPITAL LETTER O', 'LATIN SMALL LETTER M', 'ACUTE ACCENT', 'LATIN CAPITAL LETTER W', 'VULGAR FRACTION ONE QUARTER', 'PERCENT SIGN', 'LATIN CAPITAL LETTER B', 'LEFT PARENTHESIS', 'LATIN CAPITAL LETTER C', 'DIGIT NINE', 'LATIN CAPITAL LETTER Q', 'LATIN SMALL LETTER T', 'SECTION SIGN', 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX', 'CEDILLA', 'REVERSE SOLIDUS', 'SUPERSCRIPT ONE', 'LATIN SMALL LETTER A WITH ACUTE', 'LATIN SMALL LETTER D', 'LATIN CAPITAL LETTER E WITH ACUTE', 'LATIN CAPITAL LETTER K', 'LATIN SMALL LETTER U WITH ACUTE', 'QUESTION MARK', 'LATIN CAPITAL LETTER THORN', 'LATIN SMALL LETTER I', 'LATIN SMALL LETTER C', 'LATIN CAPITAL LETTER Y', 'INVERTED QUESTION MARK', 'LATIN CAPITAL LETTER Z', 'SEMICOLON', 'CENT SIGN', 'CIRCUMFLEX ACCENT', 'LATIN CAPITAL LETTER O WITH TILDE', 'QUOTATION MARK', 'MICRO SIGN', 'LATIN SMALL LETTER E WITH DIAERESIS', 'LATIN SMALL LETTER Y WITH ACUTE', 'LATIN SMALL LETTER O WITH CIRCUMFLEX', 'LATIN SMALL LETTER THORN', 'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK', 'LATIN CAPITAL LETTER P', 'LATIN CAPITAL LETTER I WITH CIRCUMFLEX', 'LATIN CAPITAL LETTER L', 'LATIN CAPITAL LETTER J', 'LATIN SMALL LETTER O WITH TILDE', 'LEFT SQUARE BRACKET', 'AMPERSAND', 'LATIN CAPITAL LETTER U WITH DIAERESIS', 'LATIN SMALL LETTER O WITH DIAERESIS', 'VULGAR FRACTION THREE QUARTERS', 'DIGIT TWO', 'LATIN SMALL LETTER Q', 'LATIN SMALL LETTER A WITH TILDE', 'RIGHT SQUARE BRACKET', 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX', 'MULTIPLICATION SIGN', 'LATIN SMALL LETTER O WITH ACUTE', 'LATIN SMALL LETTER G', 'VERTICAL LINE', 'LATIN SMALL LETTER O WITH STROKE', 'EXCLAMATION MARK', 'REGISTERED SIGN', 'LATIN SMALL LETTER O', 'DIGIT FOUR', 'COPYRIGHT SIGN', 'LATIN CAPITAL LETTER U WITH ACUTE', 'DOLLAR SIGN', 'LATIN CAPITAL LETTER E WITH GRAVE', 'DIVISION SIGN', 'BROKEN BAR', 'PLUS SIGN', 'LATIN CAPITAL LETTER S', 'LATIN CAPITAL LETTER N WITH TILDE', 'DIGIT SEVEN', 'LATIN CAPITAL LETTER N', 'LATIN CAPITAL LETTER I WITH DIAERESIS', 'LATIN CAPITAL LETTER A WITH GRAVE', 'LATIN SMALL LETTER U WITH CIRCUMFLEX', 'LATIN SMALL LETTER S', 'LATIN CAPITAL LETTER O WITH STROKE', 'LATIN CAPITAL LETTER O WITH DIAERESIS', 'LATIN CAPITAL LETTER T', 'LATIN SMALL LETTER H', 'LATIN CAPITAL LETTER F', 'GREATER-THAN SIGN', 'LATIN CAPITAL LETTER X', 'GRAVE ACCENT', 'LATIN CAPITAL LETTER Y WITH ACUTE', 'VULGAR FRACTION ONE HALF', 'DIGIT ONE', 'HYPHEN-MINUS', 'LATIN CAPITAL LETTER D', 'LATIN CAPITAL LETTER I WITH GRAVE', 'NO-BREAK SPACE', 'LATIN SMALL LETTER A'}
